// Screen/object size constants.
const WIDTH = 1285;
const HEIGHT = 655;
const ORIGINS = 0;
const ROCKET_HEIGHT = WIDTH/30;
const ROCKET_WIDTH = HEIGHT/60;
const ROCKET_X_POS = WIDTH/2;
const ROCKET_Y_POS = HEIGHT;
const TARGET_RADIUS = WIDTH/40;
const TARGET_X_POS = WIDTH/2;
const TARGET_Y_POS = HEIGHT/10;
const CRITICAL_RADIUS = TARGET_RADIUS*3/4;
const OBSTACLE_WIDTH = [WIDTH/6+100, WIDTH/6, WIDTH/6];
const OBSTACLE_HEIGHT = [Math.sqrt(OBSTACLE_WIDTH[0]), Math.sqrt(OBSTACLE_WIDTH[1]), Math.sqrt(OBSTACLE_WIDTH[2])];
const OBSTACLE_X_POS = [(WIDTH-OBSTACLE_WIDTH[0])/2, (WIDTH-OBSTACLE_WIDTH[1])/2-WIDTH/3, (WIDTH-OBSTACLE_WIDTH[2])/2+WIDTH/3];
const OBSTACLE_Y_POS = [HEIGHT*2/3, HEIGHT*2/5, HEIGHT/4];
const NUM_OBSTACLES = OBSTACLE_WIDTH.length;
const GENERATION_TEXT_X_POS = WIDTH/100;
const GENERATION_TEXT_Y_POS = HEIGHT/20;
const CYCLE_TEXT_X_POS = WIDTH/100;
const CYCLE_TEXT_Y_POS = HEIGHT/10;
const TEXT_SIZE = WIDTH/80;
// Color constants.
const RED = [255, 0, 0];
const GREEN = [0, 255, 0];
const BLUE = [0, 0, 255];
const BACKGROUND_COLOR = 10;
const TRANSPARENCY = 150;
// Population constants.
const LIFE_SPAN = 350;
const MAX_FORCE = 0.25;
const MAX_VELOCITY = 3.0;
const MUTATION_RATE = 0.01;
const POP_SIZE = 25;
